using FluentAssertions;

namespace BBRepoList.Transport.Tests;

public sealed class BitbucketErrorResponseParserTests
{
    [Fact(DisplayName = "Parse returns empty text for empty response body")]
    [Trait("Category", "Unit")]
    public void ParseWhenBodyIsEmptyReturnsEmptyText()
    {
        var parser = new BitbucketErrorResponseParser();

        var result = parser.Parse(" ", "text/html");

        result.Should().BeEmpty();
    }

    [Fact(DisplayName = "Parse returns non-HTML response body unchanged")]
    [Trait("Category", "Unit")]
    public void ParseWhenBodyIsNotHtmlReturnsBodyUnchanged()
    {
        var parser = new BitbucketErrorResponseParser();

        var result = parser.Parse("""{"error":"invalid"}""", "application/json");

        result.Should().Be("""{"error":"invalid"}""");
    }

    [Fact(DisplayName = "Parse formats HTML error response as readable text")]
    [Trait("Category", "Unit")]
    public void ParseWhenBodyIsHtmlReturnsReadableText()
    {
        const string html = """
            <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
            <HTML><HEAD><TITLE>ERROR: The request could not be satisfied</TITLE></HEAD>
            <BODY>
            <H1>403 ERROR</H1>
            <H2>The request could not be satisfied.</H2>
            <HR noshade size="1px">
            Request blocked.
            <BR clear="all">
            Generated by cloudfront (CloudFront)
            </BODY></HTML>
            """;
        var parser = new BitbucketErrorResponseParser();

        var result = parser.Parse(html, "text/html");

        result.Should().StartWith("HTML error response:");
        result.Should().Contain("ERROR: The request could not be satisfied");
        result.Should().Contain("403 ERROR");
        result.Should().Contain("Request blocked.");
        result.Should().NotContain("<HTML>");
        result.Should().NotContain("<H1>");
    }

    [Fact(DisplayName = "Parse detects HTML response without content type")]
    [Trait("Category", "Unit")]
    public void ParseWhenBodyContainsHtmlMarkerReturnsReadableText()
    {
        var parser = new BitbucketErrorResponseParser();

        var result = parser.Parse("<html><body><h1>Denied</h1></body></html>", mediaType: null);

        result.Should().Be("HTML error response: Denied");
    }
}
